### PR TITLE
Issues 78 - Makes `install.sh` more shellcheck compliant.

### PR DESCRIPTION
**Pull request by Potherca**
## Introduction

I was thinking about taking a stab at #53 but decided to make the relevant file more shellcheck compliant first (as suggested in issue #78).

### Shellcheck Fixes

All occurrences of the following issues have been resolved:

- **SC1054**: You need a space after the '{'.
- **SC2004**: $ on variables in (( )) is unnecessary.
- **SC2034**: "variable" appears unused. Verify it or export it.
- **SC2046**: Quote this to prevent word splitting.
- **SC2068**: Double quote array expansions, otherwise they're like $* and break on spaces.
- **SC2086**: Double quote to prevent globbing and word splitting.
- **SC2116**: Useless echo? Instead of 'cmd $(echo foo)', just use 'cmd foo'.

### Other issues

Whilst  resolving shellcheck issues, I ran into two problems.

1. The call `curl "${auth_param}"` caused trouble when `auth_param` is empty (`=''`). This did not happen when there were no quotes around `auth_param`, that is to say, things accidentally worked.   
  To resolve this I added a wrapper for the three use-cases around curl  with a check and two variations of calling curl (one with and one without `auth_param`.
2. In some edge-cases the `-o /dev/null` will fail with a write error (curl error 23). However, failure to write to `/dev/null` is not an issue, as the HTTP status code is still viable. To resolve this I added a separate function for the "check url exists" logic and added the check there. 

If these two solutions do not cause any trouble, I do believe they are worth keeping as they are a good first step in de-duplicating some of the curl calls.

## Work for later

The following shellcheck issues are still present as I am unsure as how to resolve them:

- **SC2059**: Don't use variables in the printf format string. Use printf "..%s.." "$foo".
- **SC2030**: Modification of script is local (to subshell caused by (..) group).
- **SC2031**: script was modified in a subshell. That change might be lost.

I would suggest fixing those issues in a separate PR  to keep things moving.

I'll continue work on #53 on a separate branch and open a PR once this has been merged to `master`.

### CODE REVIEW

**Comment by Potherca** [comment]
This PR is not (yet) in a mergable state. There is an issue caused by the six instances of `curl "${auth_param}"` that cause troube when `auth_param` is empty (`=''`).

Current status: Investigating and fixing.

**Comment by jwerle** [comment]
@Potherca thank you for this!

**Comment by jwerle** [comment]
Is this PR safe to merge in? Do you have anything else you'd like to add to it?

**Comment by Potherca** [comment]
I didn't feel too sure about the "gurl" curl wrapper so I cleaned that up by having two variations per function (wrapper) using `curl`.

Everything should be good to merge now.

**Comment by jwerle** [comment]
@Potherca awesome thanks!!

**Pull request merged**
