### PR TITLE
Simplify CI

### PR DESCRIPTION
**Pull request by szepeviktor**
Let's see the output.

### CODE REVIEW

**Comment by szepeviktor** [comment]
At home I get

```
./lib/run/run.sh:113:17: warning: eval negates the benefit of arrays. Drop eval to preserve whitespace/symbols (or eval as string). [SC2294]
./lib/run/run.sh:159:21: warning: eval negates the benefit of arrays. Drop eval to preserve whitespace/symbols (or eval as string). [SC2294]
./lib/run/run.sh:164:31: warning: eval negates the benefit of arrays. Drop eval to preserve whitespace/symbols (or eval as string). [SC2294]
```

**Comment by szepeviktor** [comment]
`ubuntu-latest` has only Shellchck v0.7
https://packages.ubuntu.com/focal/shellcheck

**Comment by szepeviktor** [comment]
Shellcheck v0.8 says 3×SC2294 about `eval`

**Comment by szepeviktor** [comment]
😉 Secret 😉 The next step could be to rewrite all code needing `shellcheck disable`.

**Comment by Potherca** [comment]
> ubuntu-latest has only Shellcheck v0.7

The same goes for Alpine (v3.15), its on 0.7.2.

> Shellcheck v0.8 says 3×SC2294 about `eval`

Yeah, I noticed... We should have time to fix things before we start using shellcheck v0.8. :+1: 

> :wink:  Secret :wink:  The next step could be to rewrite all code needing shellcheck disable.

:grin: Yes. Very true!

I hope you do not mind, I am closing this in favor of #144. The results are mostly the same, with the exception of the runner used and some changes to the `.shellcheckrc`  config file.

**Pull request closed without merging**
